import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {computeCadShape,validateCadRecipe} from '../../src/cad-kernel.mjs';
import {expandDslDocument} from '../../src/dsl-expansion.mjs';
import {SketchUpBridge} from '../../src/bridge.mjs';
import {editMockGeometry,mockGeometrySnapshot,mockGeometryRevision} from '../../src/mock-model-geometry.mjs';
const read=async n=>JSON.parse(await fs.readFile(new URL('../../examples/cad-kernel/'+n+'.json',import.meta.url)));
const n=await read('nurbs'),f=await read('curved-fillet');
const mesh=computeCadShape(n);for(const [x,y] of mesh.vertices)assert.ok(Math.abs(Math.hypot(x,y)-30)<1e-6,'rational quarter cylinder must match analytic radius');
assert.ok(mesh.vertices.some(p=>p[0]>1&&p[1]>1));
const fillet=computeCadShape(f);assert.ok(fillet.cad.evidence.valid);assert.ok(fillet.cad.evidence.volume_mm3>0);assert.ok(fillet.cad.evidence.faces>7);
const bad=structuredClone(n.recipe);bad.nodes[0].u_multiplicities=[2,2];assert.throws(()=>validateCadRecipe(bad),/multiplicities/);
assert.throws(()=>computeCadShape({...n,max_faces:3}),/budget exceeded/);
const impossible=structuredClone(f);impossible.recipe.nodes.at(-1).radius=500;assert.throws(()=>computeCadShape(impossible),/CAD_GEOMETRY_FAILED/);
const changed=structuredClone(n);changed.recipe.nodes[0].poles.forEach(row=>row[1][2]=60);const replacement=computeCadShape(changed);
const root=await fs.mkdtemp(path.join(os.tmpdir(),'cad-kernel-'));const bridge=new SketchUpBridge({mock:{sessionPath:path.join(root,'model.json')},agentContract:{rootDir:path.join(root,'tasks')},approval:{stateDir:path.join(root,'approvals')}});
await bridge.build_model({code:JSON.stringify({version:1,units:'mm',operations:[n]})});
const q=await bridge.query_model_geometry({detail:'full'}),c=q.snapshot.contexts.find(c=>c.name===n.name);assert.equal(c.cad.current,true);
const task=await bridge.edit_model_geometry({snapshot_handle:q.snapshot_handle,entity_path:c.entity_path,edits:[{op:'replace_cad',recipe:changed.recipe}],idempotency_key:'cad-reviewed-update'});assert.ok(task.ok,JSON.stringify(task));assert.notEqual(task.task_state,'failed');
const model=await bridge.mockRuntime.readModel();editMockGeometry(model,{entity_path:c.entity_path,snapshot_revision:mockGeometryRevision(model),edits:[{op:'replace_cad',recipe:changed.recipe,mesh:replacement}]});
let updated=mockGeometrySnapshot(model).contexts.find(x=>x.name===n.name);assert.equal(updated.cad.current,true);assert.equal(Math.max(...updated.vertices.map(v=>v.position[2])),60);
editMockGeometry(model,{entity_path:updated.entity_path,snapshot_revision:mockGeometryRevision(model),edits:[{op:'move_vertices',moves:[{handle:updated.vertices[0].handle,delta:[1,0,0]}]}]});updated=mockGeometrySnapshot(model).contexts.find(x=>x.name===n.name);assert.equal(updated.cad.current,false);
assert.throws(()=>editMockGeometry(model,{entity_path:updated.entity_path,snapshot_revision:mockGeometryRevision(model),edits:[{op:'replace_cad',recipe:changed.recipe,mesh:replacement}]}),/stale/);
console.log(JSON.stringify({ok:true,rational_surface_analytic:true,curved_intersection_fillet:true,invalid_knots:true,impossible_radius_rejected:true,mesh_budget:true,parametric_update:true,manual_mesh_edit_invalidates_source:true,review_route:task.task_state}));
