import assert from 'node:assert/strict';
import { freezeDetailSpecification, evaluateDetailQuality } from '../src/detail-quality.mjs';

const spec = { version: 1, required_parts: [{ id: 'panel', min_faces: 8, bounds_mm: { size: [100, 80, 10] }, geometry_checks: [{ type: 'opening', min_count: 1 }] }] };
const frozen = freezeDetailSpecification(spec);
assert.throws(() => freezeDetailSpecification({ ...spec, required_parts: [] }, frozen), /frozen/);
assert.throws(() => freezeDetailSpecification({ ...spec, max_iterations: 100 }), /1\.\.6/);
assert.throws(() => freezeDetailSpecification({ ...spec, required_views: [{ id: 'a' }, { id: 'a' }] }), /unique/);
assert.throws(() => freezeDetailSpecification({ ...spec, required_parts: [{ id: 'x', geometry_checks: [{ type: 'thickness' }] }] }), /positive min_mm/);
assert.throws(() => freezeDetailSpecification({ version: 1, required_parts: [{ id: 'x', geometry_checks: [{ type: 'declared_feature' }] }] }), /Unsupported/);
const snapshot = { groups: [{ id: 'panel', faces: 8, bounding_box: { min: [0, 0, 0], max: [100, 80, 10] }, features: [{ type: 'hole', verified: true }] }] };
const options = { snapshot, frozenSpecification: frozen, layoutQa: { ok: true, verdict: 'pass' }, runtime: 'queue', trustedSnapshot: true };
assert.equal(evaluateDetailQuality(options).quality_status, 'unverified', 'feature declarations cannot satisfy measured requirements');
snapshot.groups[0].geometry_evidence = { source: 'sketchup_runtime', measured: true, complete: true, face_count: 8, bounds_mm: { size: [100, 80, 10] }, through_holes: [{ verified: true }] };
assert.equal(evaluateDetailQuality(options).quality_accepted, true);
snapshot.groups[0].geometry_evidence.repair_strategy = 'seal_bbox';
assert.ok(evaluateDetailQuality(options).remaining.some(issue => issue.type === 'detail.bounding_box_repair_forbidden'), 'bounding box fallback must veto otherwise sufficient measured detail');
delete snapshot.groups[0].geometry_evidence.repair_strategy;
snapshot.manifold_checks = [{ op: 'manifold_repair', after: { id: 'panel', repair_strategy: 'seal_bbox' } }, { op: 'manifold_repair', after: { id: 'panel', repair_strategy: 'cleanup' } }];
assert.equal(evaluateDetailQuality(options).quality_accepted, false, 'a subsequent cleanup must not hide destructive repair history');
delete snapshot.manifold_checks;
assert.equal(evaluateDetailQuality({ ...options, trustedSnapshot: false }).quality_accepted, false, 'supplied snapshot cannot establish acceptance');
snapshot.groups[0].geometry_evidence.through_holes = [];
assert.equal(evaluateDetailQuality(options).quality_status, 'fail', 'sealed opening must fail while feature metadata is unchanged');
snapshot.groups[0].geometry_evidence.through_holes = [{ verified: true }];
snapshot.groups[0].geometry_evidence.bounds_mm.size[0] = 105;
assert.equal(evaluateDetailQuality(options).quality_status, 'fail', 'wrong measured dimensions must fail');
assert.equal(evaluateDetailQuality({ snapshot: {}, layoutQa: { ok: false, verdict: 'fail' }, trustedSnapshot: true }).quality_status, 'fail');
const shared = freezeDetailSpecification({ version: 1, required_parts: [{ id: 'leaf', instance_path: ['second', 'leaf'], min_faces: 8 }] });
const occurrence = { groups: [], geometry_occurrences: [{ part_id: 'leaf', instance_path: ['second', 'leaf'], geometry_evidence: { source: 'sketchup_runtime', measured: true, face_count: 8 } }] };
assert.equal(evaluateDetailQuality({ ...options, snapshot: occurrence, frozenSpecification: shared }).quality_accepted, true);
console.log('detail-quality: measured positives, metadata-only/removed-hole/size/forged-source negatives passed');
