# frozen_string_literal: true

# Generated by scripts/generate-plugin-runtime-source-manifest.mjs.
# Run that generator after changing an attested source file, then review and
# commit the source and manifest together.
module AlmaSketchupMCP
  module RuntimeSourceManifest
    BOOLEAN_OPERATIONS_RELATIVE_PATH = 'boolean_operations.rb'
    BOOLEAN_OPERATIONS_SHA256 = '4e23e8d35603f4d08c9c5c9c9174c99451ffcb3bd94ab233001d331beafb3b4b'
    MODEL_REVISION_RELATIVE_PATH = 'model_revision.rb'
    MODEL_REVISION_SHA256 = '1abb58211fd71c399c9c15cd467b093cdbb49fc8f9f909cb8eb687d342513b58'
  end
end
