# frozen_string_literal: true

# Generated by scripts/generate-plugin-runtime-source-manifest.mjs.
# Run that generator after changing an attested source file, then review and
# commit the source and manifest together.
module AlmaSketchupMCP
  module RuntimeSourceManifest
    BOOLEAN_OPERATIONS_RELATIVE_PATH = 'boolean_operations.rb'
    BOOLEAN_OPERATIONS_SHA256 = '4e23e8d35603f4d08c9c5c9c9174c99451ffcb3bd94ab233001d331beafb3b4b'
    MODEL_REVISION_RELATIVE_PATH = 'model_revision.rb'
    MODEL_REVISION_SHA256 = '04c97c2d154dfc7c8b3e2646614dc99cf0081a27f3db09297dfe193e2852fc1f'
  end
end
