# frozen_string_literal: true

# Generated by scripts/generate-plugin-runtime-source-manifest.mjs.
# Run that generator after changing an attested source file, then review and
# commit the source and manifest together.
module LocalMcpForSketchUp
  module RuntimeSourceManifest
    BOOLEAN_OPERATIONS_RELATIVE_PATH = 'boolean_operations.rb'
    BOOLEAN_OPERATIONS_SHA256 = '789c02466a23b2284343d279e06ca9647dc9c1b5dc4bf0523d43ed27f13124e0'
    MODEL_REVISION_RELATIVE_PATH = 'model_revision.rb'
    MODEL_REVISION_SHA256 = 'cdd500e7de0a3b7cebd3dc7e89acccdb7fc3a0bab774ae4b3c9e029e7950f301'
  end
end
